=== 119/openiot/utils/openIotCommons/src/main/resources/OSDSpec/OSDSpec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <!--
  Copyright (c) 2011-2014, OpenIoT
  
  This library is free software; you can redistribute it and/or
  modify it either under the terms of the GNU Lesser General Public
  License version 2.1 as published by the Free Software Foundation
  (the "LGPL"). If you do not alter this
  notice, a recipient may use your version of this file under the LGPL.
  
  You should have received a copy of the LGPL along with this library
  in the file COPYING-LGPL-2.1; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
  
  This software is distributed on an "AS IS" basis, WITHOUT WARRANTY
  OF ANY KIND, either express or implied. See the LGPL  for
  the specific language governing rights and limitations.
  
  Contact: OpenIoT mailto: info@openiot.eu
   
  -->
  <!--
		Author: Nikos Kefalakis (nkef@ait.edu.gr)
   -->


  <xs:element name="OSDSpec">
    <xs:annotation>
      <xs:documentation>OpenIoT Service Description Specification</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="OAMO"/>
      </xs:sequence>
      <xs:attribute name="userID" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>




  <xs:element name="OAMO">
    <xs:annotation>
      <xs:documentation>OpenIoT Application Model Object</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="description"/>
        <xs:element maxOccurs="unbounded" ref="OSMO"> </xs:element>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:anyURI"/>
      <xs:attribute name="name" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>



  <xs:element name="description" type="xs:string"> </xs:element>


  <xs:element name="OSMO">
    <xs:annotation>
      <xs:documentation>OpenIoT Sensor Model Object</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="description"/>
        <xs:element ref="queryControls"/>
        <xs:element ref="requestPresentation"/>
        <xs:element ref="query-request"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:anyURI"/>
      <xs:attribute name="name" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>


  <xs:element name="serviceID">
    <xs:complexType>
      <xs:sequence> </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="serviceName">
    <xs:complexType>
      <xs:sequence> </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="serviceDescription">
    <xs:complexType>
      <xs:sequence> </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="queryControls">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="QuerySchedule"/>
        <xs:element name="trigger" type="xs:anyURI" minOccurs="0"/>
        <xs:element name="initialRecordTime" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="reportIfEmpty" type="xs:boolean"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="QuerySchedule">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="second" type="xs:string" minOccurs="0"/>
        <xs:element name="minute" type="xs:string" minOccurs="0"/>
        <xs:element name="hour" type="xs:string" minOccurs="0"/>
        <xs:element name="dayOfMonth" type="xs:string" minOccurs="0"/>
        <xs:element name="month" type="xs:string" minOccurs="0"/>
        <xs:element name="dayOfWeek" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="requestPresentation">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="widget"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="widget">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="presentationAttr"/>
      </xs:sequence>
      <xs:attribute name="widgetID" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>


  <xs:element name="presentationAttr">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>


  <xs:element name="query-request">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="1" name="query" type="xs:string">
          <xs:annotation>
            <xs:documentation>
             (from SPARQL "protocol-types.xsd")query is an xs:string
             constrained by the language definition, 
             http://www.w3.org/TR/rdf-sparql-query/#grammar, as
             "a sequence of characters in the language defined by the
             [SPARQL] grammar, starting with the Query production"
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="default-graph-uri" type="xs:anyURI"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="named-graph-uri" type="xs:anyURI"/>
        <xs:sequence>
          <xs:element maxOccurs="unbounded" ref="dynamicAttrMaxValue"/>

        </xs:sequence>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="dynamicAttrMaxValue">
    <xs:annotation>
      <xs:documentation>Maximum/Area of Interest for the defined dynamic value</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== 119/openiot/utils/utils.commons/src/main/resources/OSDSpec/OSDSpecAutoGenaratedSampleInstance(20140124)1.xml
<?xml version="1.0" encoding="UTF-8"?>
<osd:OSDSpec xmlns:osd="urn:openiot:osdspec:xsd:1"
 xmlns:prt="http://www.w3.org/2007/SPARQL/protocol-types#"
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
 xmlns:vbr="http://www.w3.org/2007/SPARQL/results#"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="urn:openiot:osdspec:xsd:1 file:/C:/Development/Eclipse_Worksp/Eclipse_Worksp4.2.2/OpenIoT/GitHub/ait-sensap-develop/openiot/utils/utils.commons/src/main/resources/OSDSpec.xsd" userID="http://www.oxygenxml.com/">
    <osd:OAMO id="http://www.oxygenxml.com/" name="name0">
        <osd:description>description0</osd:description>
        <osd:graphMeta>graphMeta0</osd:graphMeta>
        <osd:OSMO id="http://www.oxygenxml.com/" name="name1">
            <osd:description>description1</osd:description>
            <osd:queryControls>
                <osd:QuerySchedule>
                    <osd:second>second0</osd:second>
                    <osd:minute>minute0</osd:minute>
                    <osd:hour>hour0</osd:hour>
                    <osd:dayOfMonth>dayOfMonth0</osd:dayOfMonth>
                    <osd:month>month0</osd:month>
                    <osd:dayOfWeek>dayOfWeek0</osd:dayOfWeek>
                </osd:QuerySchedule>
                <osd:trigger>http://www.oxygenxml.com/</osd:trigger>
                <osd:initialRecordTime>2006-05-04T18:13:51.0Z</osd:initialRecordTime>
                <osd:reportIfEmpty>false</osd:reportIfEmpty>
            </osd:queryControls>
            <osd:requestPresentation>
                <osd:widget widgetID="http://www.oxygenxml.com/">
                    <osd:presentationAttr name="name2" value="value0"/>
                    <osd:presentationAttr name="name3" value="value1"/>
                </osd:widget>
                <osd:widget widgetID="http://www.oxygenxml.com/">
                    <osd:presentationAttr name="name4" value="value2"/>
                    <osd:presentationAttr name="name5" value="value3"/>
                </osd:widget>
            </osd:requestPresentation>
            <prt:query-request>
                <query>query0</query>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
            </prt:query-request>
            <prt:query-request>
                <query>query1</query>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
            </prt:query-request>
            <osd:dynamicAttrMaxValue name="name6" value="value4"/>
            <osd:dynamicAttrMaxValue name="name7" value="value5"/>
        </osd:OSMO>
        <osd:OSMO id="http://www.oxygenxml.com/" name="name8">
            <osd:description>description2</osd:description>
            <osd:queryControls>
                <osd:QuerySchedule>
                    <osd:second>second1</osd:second>
                    <osd:minute>minute1</osd:minute>
                    <osd:hour>hour1</osd:hour>
                    <osd:dayOfMonth>dayOfMonth1</osd:dayOfMonth>
                    <osd:month>month1</osd:month>
                    <osd:dayOfWeek>dayOfWeek1</osd:dayOfWeek>
                </osd:QuerySchedule>
                <osd:trigger>http://www.oxygenxml.com/</osd:trigger>
                <osd:initialRecordTime>2006-05-04T18:13:51.0Z</osd:initialRecordTime>
                <osd:reportIfEmpty>false</osd:reportIfEmpty>
            </osd:queryControls>
            <osd:requestPresentation>
                <osd:widget widgetID="http://www.oxygenxml.com/">
                    <osd:presentationAttr name="name9" value="value6"/>
                    <osd:presentationAttr name="name10" value="value7"/>
                </osd:widget>
                <osd:widget widgetID="http://www.oxygenxml.com/">
                    <osd:presentationAttr name="name11" value="value8"/>
                    <osd:presentationAttr name="name12" value="value9"/>
                </osd:widget>
            </osd:requestPresentation>
            <prt:query-request>
                <query>query2</query>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
            </prt:query-request>
            <prt:query-request>
                <query>query3</query>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
            </prt:query-request>
            <osd:dynamicAttrMaxValue name="name13" value="value10"/>
            <osd:dynamicAttrMaxValue name="name14" value="value11"/>
        </osd:OSMO>
    </osd:OAMO>
    <osd:OAMO id="http://www.oxygenxml.com/" name="name15">
        <osd:description>description3</osd:description>
        <osd:graphMeta>graphMeta1</osd:graphMeta>
        <osd:OSMO id="http://www.oxygenxml.com/" name="name16">
            <osd:description>description4</osd:description>
            <osd:queryControls>
                <osd:QuerySchedule>
                    <osd:second>second2</osd:second>
                    <osd:minute>minute2</osd:minute>
                    <osd:hour>hour2</osd:hour>
                    <osd:dayOfMonth>dayOfMonth2</osd:dayOfMonth>
                    <osd:month>month2</osd:month>
                    <osd:dayOfWeek>dayOfWeek2</osd:dayOfWeek>
                </osd:QuerySchedule>
                <osd:trigger>http://www.oxygenxml.com/</osd:trigger>
                <osd:initialRecordTime>2006-05-04T18:13:51.0Z</osd:initialRecordTime>
                <osd:reportIfEmpty>false</osd:reportIfEmpty>
            </osd:queryControls>
            <osd:requestPresentation>
                <osd:widget widgetID="http://www.oxygenxml.com/">
                    <osd:presentationAttr name="name17" value="value12"/>
                    <osd:presentationAttr name="name18" value="value13"/>
                </osd:widget>
                <osd:widget widgetID="http://www.oxygenxml.com/">
                    <osd:presentationAttr name="name19" value="value14"/>
                    <osd:presentationAttr name="name20" value="value15"/>
                </osd:widget>
            </osd:requestPresentation>
            <prt:query-request>
                <query>query4</query>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
            </prt:query-request>
            <prt:query-request>
                <query>query5</query>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
            </prt:query-request>
            <osd:dynamicAttrMaxValue name="name21" value="value16"/>
            <osd:dynamicAttrMaxValue name="name22" value="value17"/>
        </osd:OSMO>
        <osd:OSMO id="http://www.oxygenxml.com/" name="name23">
            <osd:description>description5</osd:description>
            <osd:queryControls>
                <osd:QuerySchedule>
                    <osd:second>second3</osd:second>
                    <osd:minute>minute3</osd:minute>
                    <osd:hour>hour3</osd:hour>
                    <osd:dayOfMonth>dayOfMonth3</osd:dayOfMonth>
                    <osd:month>month3</osd:month>
                    <osd:dayOfWeek>dayOfWeek3</osd:dayOfWeek>
                </osd:QuerySchedule>
                <osd:trigger>http://www.oxygenxml.com/</osd:trigger>
                <osd:initialRecordTime>2006-05-04T18:13:51.0Z</osd:initialRecordTime>
                <osd:reportIfEmpty>false</osd:reportIfEmpty>
            </osd:queryControls>
            <osd:requestPresentation>
                <osd:widget widgetID="http://www.oxygenxml.com/">
                    <osd:presentationAttr name="name24" value="value18"/>
                    <osd:presentationAttr name="name25" value="value19"/>
                </osd:widget>
                <osd:widget widgetID="http://www.oxygenxml.com/">
                    <osd:presentationAttr name="name26" value="value20"/>
                    <osd:presentationAttr name="name27" value="value21"/>
                </osd:widget>
            </osd:requestPresentation>
            <prt:query-request>
                <query>query6</query>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
            </prt:query-request>
            <prt:query-request>
                <query>query7</query>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
